alias curlp="curl -X POST"
alias curld="curl -X DELETE"
alias curla="curl -X PATCH"
alias json="jq '.'"
alias iptables-all="iptables -vL -t filter && iptables -vL -t nat && iptables -vL -t mangle && iptables -vL -t raw && iptables -vL -t security"